[phases.build]
cmds = ["npx tinacms build && pnpm run build"]

[start]
cmd = "pnpm run preview"

[static]
publish = "dist"


[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true
